// This is an autogenerated file. It should match the version number in package.json.
// Do not modify this file directly.

<<<<<<< HEAD
export const SDK_VERSION = "2.3.0-rc2.2";
=======
export const SDK_VERSION = "2.3.0-rc2.3";
>>>>>>> 695e0ff146e28cfa0cdabfcbaeb1b0b2dab82b76
